import type { Locale, MessageDescriptor, MessageValues } from '../../types.js';

export type MessageKey = "checkingDataSource" | "loadingCase" | "loadingConfiguration" | "loadingContent" | "loadingOriginalFinding" | "loadingRequirements" | "loadingResults" | "loadingTactics" | "loadingTechniques" | "searching" | "activeResponse.missingSourceDescription" | "activeResponse.missingSourceTitle" | "agents.backToEndpoints" | "agents.deployNew" | "agents.noneAdded" | "agents.unpin" | "api.notReachable" | "case.cleanAction" | "case.cleanConfirmation" | "case.cleanTitle" | "case.commentAriaLabel" | "case.commentHelp" | "case.commentPlaceholder" | "case.create" | "case.emptyDescription" | "case.management" | "case.status.acknowledged" | "case.status.active" | "case.status.audit" | "case.status.completed" | "case.status.deleted" | "case.statusAriaLabel" | "case.statusHelp" | "case.tagsAriaLabel" | "case.tagsHelp" | "case.tagsPlaceholder" | "case.update" | "compliance.filterRequirements" | "compliance.hideRequirementsWithoutAlerts" | "compliance.requirement" | "compliance.requirementDescription" | "compliance.requirementWithId" | "compliance.requirements" | "compliance.requirementsColumn" | "configuration.back" | "configuration.fetchError" | "configuration.helpHintBeforeIcon" | "configuration.helpHintAfterIcon" | "configuration.notAvailable" | "configuration.sectionMissing" | "configuration.unsavedConfirmation" | "configuration.unsavedTitle" | "daemons.generalStatusAria" | "daemons.readyRunningStatus" | "daemons.readyStatus" | "daemons.statusAria" | "daemons.title" | "dashboardRenderer.errorTitle" | "dashboardRenderer.failedTitle" | "dashboardRenderer.notFoundMessage" | "dashboardRenderer.notFoundTitle" | "dashboardRenderer.unavailableDescription" | "dashboardRenderer.unavailableTitle" | "decoders" | "discover.searchColumns" | "groups.availableAgents" | "groups.back" | "groups.changeLimitExceeded" | "groups.currentAgentsCount" | "groups.errorFetchingAvailableAgents" | "groups.errorFetchingGroupAgents" | "groups.errorLoadingAgents" | "groups.loadMoreAgents" | "groups.manageAgents" | "groups.updated" | "indexerManagement" | "mitre.alertsFetchError" | "mitre.filterSelectedTacticTechniques" | "mitre.hideTechniquesWithoutAlerts" | "mitre.openDetailsInIntelligence" | "mitre.tactics" | "mitre.tacticsOptions" | "mitre.techniqueDetails" | "mitre.techniqueFetchError" | "mitre.techniques" | "mitre.techniquesFetchError" | "mitre.viewTechniqueDetails" | "mitreAttack" | "openMitreAttack" | "ruleTitle" | "security.roleMapping.deleteAction" | "security.roleMapping.deleteConfirmation" | "security.roleMapping.deleted" | "security.roleMapping.reservedDeleteDisabled" | "security.roleMapping.wuiOwnership" | "view.dashboard" | "view.events" | "vulnerabilities.details" | "vulnerabilities.inspectDetails";
export declare const packId: "wazuh";
export declare const messages: Readonly<Record<MessageKey, MessageDescriptor>>;
export declare const osdMessages: Readonly<Record<string, string>>;
export declare const formats: Readonly<Record<string, unknown>>;
export declare function translate(key: MessageKey, values?: MessageValues | Locale, locale?: Locale): string;
export declare function variants(key: MessageKey): string[];
