import type { Locale, MessageDescriptor, MessageValues } from '../../types.js';

export type MessageKey = "action" | "allItems" | "appearance" | "back" | "cancel" | "close" | "closeModal" | "collapse" | "colorLabel" | "column" | "confirm" | "copyValue" | "createWorkspace" | "delete" | "description" | "development" | "dismiss" | "error" | "errorDetails" | "expand" | "filter" | "filterForValue" | "filterOutValue" | "global" | "home" | "info" | "inputTokens" | "learnMore" | "loading" | "loadingContent" | "manage" | "nameLabel" | "navigation" | "notAvailable" | "noResults" | "notifications" | "outputTokens" | "pages" | "private" | "recentlyViewed" | "reserved" | "response" | "search" | "searchPlaceholder" | "success" | "tokens" | "type" | "unknownError" | "useCaseLabel" | "viewAll" | "actions" | "addAllItems" | "addSelectedItems" | "addedCount" | "agent" | "agentName" | "agents" | "applications" | "applyChanges" | "comment" | "configuration" | "createdAt" | "details" | "edit" | "errorDownloadingCsvReport" | "errorFetchingData" | "exportFormatted" | "files" | "filterAction" | "filterByField" | "goals" | "group" | "icon" | "id" | "inspectItemInApp" | "inspectDetails" | "inspectDocumentDetails" | "integration" | "loadingEllipsis" | "moreItems" | "more" | "name" | "no" | "noDoNotProceed" | "notReady" | "operatingSystem" | "operatingSystemName" | "operatingSystemVersion" | "options" | "queryLimitFirstHits" | "queryLimitRefineSearch" | "ready" | "recentEvents" | "refresh" | "reload" | "removeAllItems" | "removeSelectedItems" | "removedCount" | "reset" | "retry" | "roles" | "selectAll" | "showItemInApp" | "stats" | "status" | "tags" | "time" | "timestamp" | "unexpectedError" | "unselectAll" | "updatedAt" | "user" | "version" | "viewDetailsOfItem" | "yes" | "yesProceed";
export declare const packId: "common";
export declare const messages: Readonly<Record<MessageKey, MessageDescriptor>>;
export declare const osdMessages: Readonly<Record<string, string>>;
export declare const formats: Readonly<Record<string, unknown>>;
export declare function translate(key: MessageKey, values?: MessageValues | Locale, locale?: Locale): string;
export declare function variants(key: MessageKey): string[];
